services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'

  app:
    image: node:latest
    container_name: api
    restart: always
    depends_on:
      - postgres
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/src/app
    command: bash -c "npm i && npm run build && node dist/src/server.js"
    working_dir: /usr/src/app
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
