services:
  # app:
  #   image: teste
  #   build: .
  #   command: npm run dev
  #   depends_on:
  #     - postgres
  #   ports:
  #     - '3333:3333'
  #   volumes:
  #     - .:/usr/app

  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
